src/main/java/micdoodle8/mods/galacticraft/core/client/gui/screen/GuiJoinSpaceRace.java, src/main/java/micdoodle8/mods/galacticraft/core/entities/EntityAlienVillager.java, src/main/java/micdoodle8/mods/galacticraft/core/entities/EntitySkeletonBoss.java
Here for missing minor translations
=> Some fixes

src/main/java/micdoodle8/mods/galacticraft/core/tile/TileEntityParaChest.java
=> Fix partial fuel canister not filled in parachest

src/main/java/micdoodle8/mods/galacticraft/core/entities/EntityBuggy.java
This should fix #1324 and #1297.
=> Moon Buggy fixes

src/main/java/micdoodle8/mods/galacticraft/core/world/gen/dungeon/MapGenDungeon.java
If planets has oxygen atmosphere.
=> Make dungeon generated vanilla torch

src/main/java/micdoodle8/mods/galacticraft/core/blocks/BlockAluminumWire.java
=> Fix aluminum wire hitboxes too small

src/main/java/micdoodle8/mods/galacticraft/planets/mars/blocks/BlockSludge.java
I think that should fix for this.
=> Fix sludge rendering. Fixes #1111

src/main/java/micdoodle8/mods/galacticraft/core/client/gui/screen/GuiCelestialSelection.java
That too slow when I moving map.
=> Improved ASWD key movement

src/main/java/micdoodle8/mods/galacticraft/planets/mars/entities/EntitySlimeling.java
=> Improvement Slimeling hurt sound

src/main/java/micdoodle8/mods/galacticraft/planets/mars/tile/TileEntityTerraformer.java
See also on Oxygen Distributor when placing block.
=> Fix Terraform Bubble spawning glitch (F3 + B)

src/main/java/micdoodle8/mods/galacticraft/planets/mars/client/render/item/ItemRendererMachine.java
=> Fix ghost Item Stack rendering

src/main/resources/assets/galacticraftmars/lang/ja_JP.lang
Woohoo, half of Mars is translated now. The rest is coming soon.
=> Update ja_JP.lang - Mars in Japanese

src/main/resources/assets/galacticraftmars/lang/it_IT.lang
This is the italian translation for Galacticraft Mars. Next week I will translate GalacticraftAsteroids and GalacrticraftMoon. :D
=> GalacrticraftMars - Italian Translation

src/main/resources/assets/galacticraftcore/lang/de_DE.lang
This merges commit f7e66ce  into de_DE.lang :) .
=> [de_DE.lang] Shorten in-game config localizations

src/main/java/micdoodle8/mods/galacticraft/planets/asteroids/blocks/BlockBasicAsteroids.java
=> Removed @SideOnly(Side.CLIENT)

src/main/resources/assets/galacticraftcore/models/item/dungeon_key.json
=> Added Dungeon Key model for 1.8

src/main/java/micdoodle8/mods/galacticraft/core/energy/EnergyUtil.java, src/main/java/micdoodle8/mods/galacticraft/core/energy/grid/EnergyNetwork.java
Fixed a few typos related to commit 12020e5
=> Fixed a few typos

src/main/java/micdoodle8/mods/galacticraft/core/client/gui/container/GuiExtendedInventory.java
=> Fix block lighting in NEI Panel

src/main/java/micdoodle8/mods/galacticraft/core/blocks/BlockFluidGC.java, src/main/java/micdoodle8/mods/galacticraft/core/blocks/BlockSpinThruster.java, src/main/java/micdoodle8/mods/galacticraft/core/client/fx/EffectHandler.java, src/main/java/micdoodle8/mods/galacticraft/core/client/fx/EntityFXOilDrip.java, src/main/java/micdoodle8/mods/galacticraft/core/world/gen/StructureComponentVillageField.java, src/main/java/micdoodle8/mods/galacticraft/core/world/gen/StructureComponentVillageField2.java, src/main/java/micdoodle8/mods/galacticraft/core/world/gen/StructureComponentVillageWell.java, src/main/java/micdoodle8/mods/galacticraft/core/world/gen/StructureVillagePiecesMoon.java, src/main/java/micdoodle8/mods/galacticraft/planets/asteroids/blocks/AsteroidBlocks.java, src/main/java/micdoodle8/mods/galacticraft/planets/asteroids/recipe/RecipeManagerAsteroids.java, src/main/java/micdoodle8/mods/galacticraft/planets/asteroids/tile/TileEntityTreasureChestAsteroids.java, src/main/java/micdoodle8/mods/galacticraft/planets/mars/MarsModuleClient.java, src/main/java/micdoodle8/mods/galacticraft/planets/mars/blocks/BlockSludge.java, src/main/java/micdoodle8/mods/galacticraft/planets/mars/client/fx/EntityBacterialDripFX.java, src/main/java/micdoodle8/mods/galacticraft/planets/mars/tile/TileEntityTreasureChestMars.java
1. Added Oil and Bacterial Sludge dripping particles
2. Changing Moon Village gen block
3. Added Ore Dictionary Support for Asteroid Block
4. Treasure Chest not consume Dungeon Key in the creative mode
=> More improvement for 1.7.10

src/main/resources/assets/galacticraftcore/lang/de_DE.lang
* Translated new strings
* Updated / Corrected some strings
=> Updated de_DE.lang

src/main/java/micdoodle8/mods/galacticraft/core/client/gui/container/GuiCoalGenerator.java
=> Improve Coal Generator GUI

src/main/java/micdoodle8/mods/galacticraft/core/client/gui/screen/GameScreenText.java, src/main/resources/assets/galacticraftcore/lang/en_US.lang, src/main/resources/assets/galacticraftcore/lang/th_TH.lang
=> Closed #1167. Add translation for "No link"

src/main/java/micdoodle8/mods/galacticraft/api/client/tabs/TabRegistry.java
changed event.gui.buttonList to event.buttonList. Before changing this I got an error saying that event.gui.buttonList is not visible. Is there something I didn't consider? After changing it I was able to add a tab.
=> Update TabRegistry.java, event.gui.buttonList

src/main/java/micdoodle8/mods/galacticraft/core/entities/player/PlayerClient.java
Please let me know if this break things in Galacticraft.
=> Fix player can jumping on a non-solid block

src/main/java/micdoodle8/mods/galacticraft/core/blocks/BlockLandingPad.java
=> Fix extra lag when place landing pad

src/main/java/micdoodle8/mods/galacticraft/core/client/render/entities/layer/LayerThermalPadding.java
=> Fix block breaking animation rendering

src/main/java/micdoodle8/mods/galacticraft/core/GalacticraftCore.java, src/main/java/micdoodle8/mods/galacticraft/core/entities/player/PlayerClient.java
Just a quick and dirty fix for a specific issue with specific conflicting mods
=> Dont change height if conflicting mods are present. This fixes #2158, fixes #2309

src/main/java/micdoodle8/mods/galacticraft/planets/venus/client/render/entity/RenderEntryPodVenus.java
=> Fix Venus Entry Pod rendering

src/main/java/micdoodle8/mods/galacticraft/core/entities/player/PlayerClient.java, src/main/java/micdoodle8/mods/galacticraft/core/util/ConfigManagerCore.java
=> Added a config option to disable camera changes when entering a vehicle

src/main/java/micdoodle8/mods/galacticraft/core/client/render/entities/RenderPlayerGC.java
Very bad code for a render of thermal armor in add-ons.
=> Render of thermal armor in add-ons.

src/main/java/micdoodle8/mods/galacticraft/planets/mars/client/gui/GuiSlimelingFeed.java
=> Fixed cannot exit Feed GUI

src/main/java/micdoodle8/mods/galacticraft/core/GalacticraftCore.java, src/main/java/micdoodle8/mods/galacticraft/core/tile/TileEntityNull.java, src/main/java/micdoodle8/mods/galacticraft/planets/asteroids/blocks/BlockWalkway.java
=> Fix Walkway lag

src/main/java/micdoodle8/mods/galacticraft/core/GCBlocks.java, src/main/java/micdoodle8/mods/galacticraft/core/blocks/BlockNasaWorkbench.java, src/main/java/micdoodle8/mods/galacticraft/core/items/ItemBlockNasaWorkbench.java
=> Improve Nasa Workbench block placement

src/main/java/micdoodle8/mods/galacticraft/core/client/model/ModelBipedGC.java
=> Fix player model #2463

src/main/java/micdoodle8/mods/galacticraft/core/tick/TickHandlerClient.java
=> Enable Remove "Press shift to dismount" again

src/main/java/micdoodle8/mods/galacticraft/core/blocks/BlockFallenMeteor.java, src/main/resources/assets/galacticraftcore/models/block/fallen_meteor_model.json
=> Fix meteor block color

src/main/java/micdoodle8/mods/galacticraft/planets/asteroids/client/render/entity/RenderAstroMiner.java
Also clean up GL11 to GlStateManager. Part of #2492
After fix
=> Fix Astro Miner rendering

src/main/java/micdoodle8/mods/galacticraft/core/client/gui/overlay/OverlayRocket.java
=> Fix rocket overlay player head rendering

src/main/java/micdoodle8/mods/galacticraft/core/blocks/BlockBrightLamp.java, src/main/java/micdoodle8/mods/galacticraft/core/blocks/BlockFluidTank.java, src/main/java/micdoodle8/mods/galacticraft/core/blocks/BlockSpinThruster.java, src/main/java/micdoodle8/mods/galacticraft/planets/venus/blocks/BlockCrashedProbe.java, src/main/java/micdoodle8/mods/galacticraft/planets/venus/blocks/BlockTorchWeb.java
=> Some bug fixes

src/main/java/micdoodle8/mods/galacticraft/core/client/model/ModelBipedGC.java
=> Fix player model too low 1-pixel

src/main/java/micdoodle8/mods/galacticraft/core/client/render/entities/layer/LayerFrequencyModule.java
=> Fix Frequency Module position while sneaking. #2605

src/main/java/micdoodle8/mods/galacticraft/core/client/render/tile/TileEntityArclampRenderer.java
=> Arclamp Tile Entity rendering. Fixes #2603

src/main/java/micdoodle8/mods/galacticraft/core/blocks/BlockSpinThruster.java
Wrench doesn't do anything with Thruster, not sure why.
=> Fix Spin Thruster can't stay on block. #2601

src/main/java/micdoodle8/mods/galacticraft/planets/mars/client/gui/GuiSlimeling.java, src/main/java/micdoodle8/mods/galacticraft/planets/mars/client/gui/GuiSlimelingInventory.java
=> Fix Slimeling GUI rendering

src/main/java/micdoodle8/mods/galacticraft/planets/mars/client/gui/GuiSlimelingInventory.java
=> Ignored black background in Slimeling Inventory

src/main/java/micdoodle8/mods/galacticraft/planets/mars/client/gui/GuiSlimeling.java
Features :
Support with Ctrl + A/C/X
Please let me know if I miss current feature of Slimeling GUI.
I will implement this #2110 in the future.
=> Rewrite Slimeling Rename text box

src/main/java/micdoodle8/mods/galacticraft/planets/mars/client/gui/GuiSlimeling.java
Request from @EzerArch. https://github.com/micdoodle8/Galacticraft/pull/2665#issuecomment-298445607
=> Added Slimeling Favorite Food tooltip

src/main/java/micdoodle8/mods/galacticraft/core/util/GCCoreUtil.java
A simple check for dev environment
See also : https://github.com/MCCommanderTH/IndicatorUtils/blob/master/1.11.2/src/main/java/stevekung/mods/indicatorutils/IndicatorUtils.java#L161
=> Add fml.deobfuscatedEnvironment

src/main/java/micdoodle8/mods/galacticraft/core/client/render/item/ItemModelBuggy.java, src/main/java/micdoodle8/mods/galacticraft/core/client/render/item/ItemModelFlag.java, src/main/java/micdoodle8/mods/galacticraft/core/client/render/item/ItemModelRocket.java, src/main/java/micdoodle8/mods/galacticraft/core/client/render/item/ItemModelWorkbench.java, src/main/java/micdoodle8/mods/galacticraft/planets/asteroids/client/render/item/ItemModelAstroMiner.java, src/main/java/micdoodle8/mods/galacticraft/planets/asteroids/client/render/item/ItemModelBeamReceiver.java, src/main/java/micdoodle8/mods/galacticraft/planets/asteroids/client/render/item/ItemModelBeamReflector.java, src/main/java/micdoodle8/mods/galacticraft/planets/asteroids/client/render/item/ItemModelCargoRocket.java, src/main/java/micdoodle8/mods/galacticraft/planets/asteroids/client/render/item/ItemModelGrapple.java, src/main/java/micdoodle8/mods/galacticraft/planets/asteroids/client/render/item/ItemModelRocketT3.java, src/main/java/micdoodle8/mods/galacticraft/planets/asteroids/client/render/item/ItemModelTelepad.java, src/main/java/micdoodle8/mods/galacticraft/planets/mars/client/render/item/ItemModelRocketT2.java
More bug fixes today xD
But a buggy first person render doesn't match the third person item render.
=> Fix item rendering

src/main/java/micdoodle8/mods/galacticraft/core/client/gui/overlay/OverlayOxygenWarning.java
=> Fix oxygen warning message rendering

CONTRIBUTING.md
Publicly Open Source for now :D
=> Update More Planets Repository URL

src/main/java/micdoodle8/mods/galacticraft/core/tile/TileEntitySpaceStationBase.java
=> Remove unused NBT data from Space Station Block

src/main/java/micdoodle8/mods/galacticraft/core/client/render/entities/RenderEvolvedCreeper.java, src/main/java/micdoodle8/mods/galacticraft/core/client/render/entities/layer/LayerEvolvedCreeperCharge.java, src/main/java/micdoodle8/mods/galacticraft/core/client/render/entities/layer/LayerEvolvedEndermanEyes.java, src/main/java/micdoodle8/mods/galacticraft/core/client/render/entities/layer/LayerEvolvedEndermanHeldBlock.java
Also refactoring parameter names, clean up code and fix charged creeper render layer.
=> Fix Evolved Creeper model floating

src/main/java/micdoodle8/mods/galacticraft/core/client/jei/ingotcompressor/IngotCompressorShapedRecipeWrapper.java, src/main/java/micdoodle8/mods/galacticraft/core/client/jei/ingotcompressor/IngotCompressorShapelessRecipeWrapper.java
=> Added XP Smelting info to Ingot Compressor JEI recipe

src/main/java/micdoodle8/mods/galacticraft/core/client/jei/GalacticraftJEI.java, src/main/java/micdoodle8/mods/galacticraft/planets/asteroids/client/jei/GalacticraftAsteroidsJEI.java, src/main/java/micdoodle8/mods/galacticraft/planets/mars/client/jei/GalacticraftMarsJEI.java
=> JEI Improvement

src/main/java/micdoodle8/mods/galacticraft/planets/mars/blocks/MarsBlocks.java
=> Added ore dict for Desh Block, Fix for Issue #3012

src/main/java/micdoodle8/mods/galacticraft/core/recipe/RecipeManagerGC.java
In Galacticraft you couldn't use BiomesOPlenty sticks for GC tools nor could you use Industrial Diamonds from IC2 in recipes, so I have added it in via oreDict along with other changes to recipes.
=> Added OreDict values in recipes for vanilla items and blocks.

src/main/java/micdoodle8/mods/galacticraft/core/client/model/ModelEvolvedSkeletonBoss.java, src/main/java/micdoodle8/mods/galacticraft/core/client/render/entities/RenderBuggy.java, src/main/java/micdoodle8/mods/galacticraft/core/client/render/entities/RenderEvolvedSkeleton.java, src/main/java/micdoodle8/mods/galacticraft/core/client/render/entities/RenderEvolvedSkeletonBoss.java, src/main/java/micdoodle8/mods/galacticraft/core/client/render/entities/RenderFlag.java, src/main/java/micdoodle8/mods/galacticraft/core/client/render/entities/layer/LayerFrequencyModule.java, src/main/java/micdoodle8/mods/galacticraft/core/client/render/entities/layer/LayerHeldItemEvolvedSkeletonBoss.java, src/main/java/micdoodle8/mods/galacticraft/core/client/render/entities/layer/LayerOxygenGear.java, src/main/java/micdoodle8/mods/galacticraft/core/client/render/entities/layer/LayerOxygenMask.java, src/main/java/micdoodle8/mods/galacticraft/core/client/render/entities/layer/LayerOxygenTanks.java, src/main/java/micdoodle8/mods/galacticraft/planets/asteroids/client/render/entity/RenderAstroMiner.java, src/main/java/micdoodle8/mods/galacticraft/planets/asteroids/client/render/entity/RenderEntryPod.java, src/main/java/micdoodle8/mods/galacticraft/planets/asteroids/client/render/entity/RenderTier3Rocket.java, src/main/java/micdoodle8/mods/galacticraft/planets/mars/client/render/entity/RenderCargoRocket.java, src/main/java/micdoodle8/mods/galacticraft/planets/mars/client/render/entity/RenderLandingBalloons.java, src/main/java/micdoodle8/mods/galacticraft/planets/mars/client/render/entity/RenderTier2Rocket.java, src/main/java/micdoodle8/mods/galacticraft/planets/venus/client/render/entity/RenderSpiderQueen.java, src/main/java/micdoodle8/mods/galacticraft/planets/venus/client/render/entity/RenderWebShot.java
Some screenshots
Fixes #1983
NOTE: Please review this before merge into branch. Thanks!
=> Fix all Entity rendering

src/main/java/micdoodle8/mods/galacticraft/core/client/render/tile/TileEntityArclampRenderer.java, src/main/java/micdoodle8/mods/galacticraft/planets/asteroids/client/render/tile/TileEntityBeamReceiverRenderer.java, src/main/java/micdoodle8/mods/galacticraft/planets/asteroids/client/render/tile/TileEntityBeamReflectorRenderer.java
Before and After
Fixes #2603
~~Note : Do not merge this! I've found problem when GUI Tooltip is rendered. That make Tile Entity lighting glitches.~~
~~Still try to fix it.~~
Edit: Fixed!
=> Tile entity lighting fixes

src/main/java/micdoodle8/mods/galacticraft/api/prefab/entity/EntitySpaceshipBase.java
Seems to be a MC 1.10+ issue :P 
Fixes issue #3025
=> [1.10+] Fixed issue #3025 - Rocket not exploding when hitting the ground

src/main/java/micdoodle8/mods/galacticraft/core/client/render/entities/layer/LayerOxygenTanks.java
=> Fix Creative Oxygen Tank check in layer renderer

src/main/java/micdoodle8/mods/galacticraft/core/blocks/BlockFluidGC.java, src/main/java/micdoodle8/mods/galacticraft/planets/mars/blocks/BlockSludge.java, src/main/java/micdoodle8/mods/galacticraft/planets/venus/blocks/BlockSulphuricAcid.java
This is just a simple fix, please let me know if you want to add more behavior. Thanks!
Note : This method available only 1.10+.
Fixed #1623, Fixed #3005, Fixed #3145 and other related issues.
=> Make GC Fluid can be swim and can't breath inside of it

src/main/java/micdoodle8/mods/galacticraft/core/entities/player/GCPlayerHandler.java
=> Fix oxygen consumption from ballons without a mask and an oxygen gear

src/main/java/micdoodle8/mods/galacticraft/planets/venus/VenusModule.java
https://en.wikipedia.org/wiki/Atmosphere_of_Venus
Carbon dioxide 96.5 %
Nitrogen	3.5 %
=> Add atmosphere component on Venus

src/main/java/micdoodle8/mods/galacticraft/core/tile/TileEntityEmergencyBox.java
Step to reproduce.
1. Place tallgrass at the any side of Emergency Box.
2. Open Emergency Box.
Crash Log : https://pastebin.com/rCL6sDgw
=> Fix crash with Emergency Box

src/main/java/micdoodle8/mods/galacticraft/planets/mars/recipe/RecipeManagerMars.java
Just changes `Items.slime_ball` to `slimeball` for the oreDictionary.
=> (#3401) Use the ore dictionary entry for the slimeball

src/main/java/micdoodle8/mods/galacticraft/core/recipe/RecipeManagerGC.java
See [previous pull request](https://github.com/micdoodle8/Galacticraft/pull/3579).
=> Updated Cheese Block Recipe to use OreDictionaty value

src/main/java/micdoodle8/mods/galacticraft/api/GalacticraftRegistry.java
Im requesting this game because i need it for my Galacticraft Tweaker mod, Would be amazing if it could be merged
=> Allow for Tier 1 - 3 rocket, Cargo Rocket, Moon buggy,  Astro Miner recipes to be removed

readme.md
Adds a discord badge,, build status badge, and patreon badge.
Also makes 'making PRs' and 'reporting issues' go under 'Contributing'
=> Add badges to readme

src/main/java/micdoodle8/mods/galacticraft/core/proxy/ClientProxyCore.java
I missed a bit of debug logging... and forgot to put braces on new lines.
I also cleaned up the way the lines are split up
=> Cape cleanup

src/main/java/micdoodle8/mods/galacticraft/planets/venus/client/render/tile/TileEntityLaserTurretRenderer.java
=> Laser Lighting Improvement, Using GlStateManager

src/main/java/micdoodle8/mods/galacticraft/core/entities/EntityBuggy.java
(Also makes it a bit wider)
Allows shooting arrows at things closer to you w/o breaking the buggy
It doesn't seem to affect climbing stuff too
=> Make the buggy hitbox shorter

src/main/java/micdoodle8/mods/galacticraft/api/prefab/entity/EntitySpaceshipBase.java, src/main/java/micdoodle8/mods/galacticraft/api/prefab/entity/EntityTieredRocket.java, src/main/java/micdoodle8/mods/galacticraft/core/advancement/GCTriggers.java, src/main/java/micdoodle8/mods/galacticraft/core/advancement/criterion/GenericTrigger.java, src/main/java/micdoodle8/mods/galacticraft/core/entities/EntitySkeletonBoss.java
Fix the reflection code to check if the method has at *least* 1 param
Move Rocket Launch trigger to `EntitySpaceshipBase`
Fix code format
Actually test/check if the trigger was validly triggered
`KILL_MOON_BOSS` -> `FIND_MOON_BOSS` (whoops!)
This should fix #3828, fix #3837, fix #3844
=> General Advancement Fixes/Improvements

src/main/resources/assets/galacticraftcore/models/block/fuel_loader_model.json
The texture was that of oil instead of fuel input
=> fixed fuel input texture

src/main/java/micdoodle8/mods/galacticraft/core/blocks/BlockAdvanced.java, src/main/java/micdoodle8/mods/galacticraft/core/blocks/BlockCargoLoader.java, src/main/java/micdoodle8/mods/galacticraft/core/blocks/BlockFuelLoader.java, src/main/java/micdoodle8/mods/galacticraft/core/blocks/BlockMachineBase.java, src/main/java/micdoodle8/mods/galacticraft/core/blocks/BlockOxygenCollector.java, src/main/java/micdoodle8/mods/galacticraft/core/blocks/BlockOxygenCompressor.java, src/main/java/micdoodle8/mods/galacticraft/core/blocks/BlockOxygenDistributor.java, src/main/java/micdoodle8/mods/galacticraft/core/blocks/BlockOxygenSealer.java, src/main/java/micdoodle8/mods/galacticraft/core/blocks/BlockRefinery.java, src/main/java/micdoodle8/mods/galacticraft/core/blocks/BlockSolar.java, src/main/java/micdoodle8/mods/galacticraft/core/energy/tile/TileBaseUniversalElectrical.java, src/main/java/micdoodle8/mods/galacticraft/core/items/ItemUniversalWrench.java, src/main/java/micdoodle8/mods/galacticraft/planets/mars/blocks/BlockMachineMars.java, src/main/java/micdoodle8/mods/galacticraft/planets/venus/blocks/BlockSolarArrayController.java
Changes wrench logic to rotate *any* block with "facing" property
https://streamable.com/4k05r
=> Make wrench logic more "universal"

src/main/java/micdoodle8/mods/galacticraft/planets/asteroids/entities/EntityGrapple.java, src/main/java/micdoodle8/mods/galacticraft/planets/asteroids/items/ItemGrappleHook.java
=> Use "string" Ore Dictionary values rather than hardcoding the item.

src/main/java/micdoodle8/mods/galacticraft/planets/venus/tile/TileEntityLaserTurret.java
=> Laser turret will no longer target tamed entities

src/main/java/micdoodle8/mods/galacticraft/api/world/IOrbitDimension.java, src/main/java/micdoodle8/mods/galacticraft/core/client/gui/screen/GuiCelestialSelection.java, src/main/java/micdoodle8/mods/galacticraft/core/dimension/WorldProviderOverworldOrbit.java, src/main/java/micdoodle8/mods/galacticraft/core/network/PacketSimple.java, src/main/java/micdoodle8/mods/galacticraft/core/tick/TickHandlerServer.java, src/main/java/micdoodle8/mods/galacticraft/core/wrappers/ScheduledDimensionChange.java
=> Get world by dimension id, rather than name

src/main/java/micdoodle8/mods/galacticraft/core/blocks/BlockMulti.java, src/main/java/micdoodle8/mods/galacticraft/core/blocks/BlockTier1TreasureChest.java, src/main/java/micdoodle8/mods/galacticraft/core/client/gui/overlay/OverlayDockingRocket.java, src/main/java/micdoodle8/mods/galacticraft/core/client/gui/overlay/OverlayLander.java, src/main/java/micdoodle8/mods/galacticraft/core/client/gui/overlay/OverlayLaunchCountdown.java, src/main/java/micdoodle8/mods/galacticraft/core/client/gui/overlay/OverlayOxygenTanks.java, src/main/java/micdoodle8/mods/galacticraft/core/client/gui/overlay/OverlayOxygenWarning.java, src/main/java/micdoodle8/mods/galacticraft/core/client/gui/overlay/OverlayRocket.java, src/main/java/micdoodle8/mods/galacticraft/core/tick/TickHandlerClient.java, src/main/java/micdoodle8/mods/galacticraft/planets/mars/client/gui/GuiMethaneSynthesizer.java, src/main/java/micdoodle8/mods/galacticraft/planets/venus/blocks/BlockTorchWeb.java
- Make Solar Pole (Top) bounding box same as Solar Top layer
- Correct Treasure Chest block sound
- Overlay classes cleanup (Fixed message blink too fast)
- Remove unused InfoRegion in Methane Synthesizer GUI
- Make Oxygen Tank Indicator should not render when in creative mode
- Fixed Web Torch placement logic
=> Bug fixes/Improvement

src/main/java/micdoodle8/mods/galacticraft/api/vector/BlockVec3.java
https://github.com/micdoodle8/Galacticraft/issues/4020
=> Fix handling of null facing in getTileEntityOnSide
