micdoodle8/Galacticraft

src/main/java/micdoodle8/mods/galacticraft/core/client/gui/container/GuiExtendedInventory.java

Please let's me know if this conflict with something.
Before
After

Fix lighting in extended inventory

---

src/main/java/micdoodle8/mods/galacticraft/api/galaxies/GalaxyRegistry.java

I was playing around with dynamic solar system generation and came over a weird bug where planets are duplicated in the GuiCelestialSelection when GalaxyRegistry.refreshGalaxies is called. Looks like you forgot to clear the third hashmap in there.

fixed duplicate planets on live galaxyregistry refresh

---

src/main/java/micdoodle8/mods/galacticraft/core/client/gui/element/GuiElementTextBox.java
src/main/java/micdoodle8/mods/galacticraft/planets/mars/client/gui/GuiLaunchController.java

Currently, it is possible to fly to other player's space station with a launch controller if a player forgot to remove the destination ID. This scrambles the ID of the launch controller and it will be impossible to see where you are going.
It will still be possible to use the launch controller and look at the destination's controller. But it's easy to scramble that one too, in case you are interested.
Of course, it might be better to add a check to see if the player are in the same space race team. Or add a button which completely locks off players of other space race teams, but this was the easiest implementation I could think if.
This circumvention is just something which bugged me for a long time.

Scramble the destination of the launch controller

---

src/main/java/micdoodle8/mods/galacticraft/core/GalacticraftCore.java

#1321
An UnsatisfiedLinkError is an Error, and is not an Exception. Catching Exception will not match it.

Actually fix OpenJDK

---

src/main/java/micdoodle8/mods/galacticraft/core/entities/EntityAdvanced.java
src/main/java/micdoodle8/mods/galacticraft/core/network/NetworkUtil.java
src/main/java/micdoodle8/mods/galacticraft/core/tile/TileEntityAdvanced.java
src/main/java/micdoodle8/mods/galacticraft/core/wrappers/FlagData.java

When we first tested GC and placed down some blocks 2 months ago, we were noticing excessive bandwidth usage (>5 mbit/s) and it was kicking some of us off due to overflow.
However, I was unable to find any reports of the issue on the Internet.
I traced our problem to some TEs that were presumably sending their data constantly to the client and I created the included patches. We applied them to our modpack and server and it seemed to have (mostly) abated our bandwidth usage problems for the past month and a half.
This PR makes some changes to EntityAdvanced and TileEntityAdvanced so that it keeps track of the previous values sent and only sends off a packet if there were changes detected. It would not reduce high bandwidth usage if data is changing often, but it reduces idle bandwidth …

Add data field change tracking to reduce bandwidth usage

---

src/main/java/micdoodle8/mods/galacticraft/core/tick/TickHandlerServer.java

Once in a blue moon, our server freezes up for a solid 30+ seconds in onWorldTick(). A few stack dumps have pointed to the CopyOnWriteArrayList used to store pending block changes:
```
at java.util.Arrays.copyOf(Arrays.java:3181)
at java.util.concurrent.CopyOnWriteArrayList.add(CopyOnWriteArrayList.java:439)
at micdoodle8.mods.galacticraft.core.tick.TickHandlerServer.onWorldTick(TickHandlerServer.java:492)
at cpw.mods.fml.common.eventhandler.ASMEventHandler_984_TickHandlerServer_onWorldTick_WorldTickEvent.invoke(.dynamic)
at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:268)
at …
```

Make TickHandlerServer.onWorldTick() faster

---

src/main/java/micdoodle8/mods/galacticraft/core/items/GCItems.java

Because ore dictionary are not register correctly.

Fix Ore Dictionary warning in Forge Build 1541

---

src/main/java/micdoodle8/mods/galacticraft/core/command/CommandPlanetTeleport.java
src/main/java/micdoodle8/mods/galacticraft/core/world/gen/MapGenCavesMoon.java

After cave generation has been fixed.

Some cave and command fix

---

src/main/java/micdoodle8/mods/galacticraft/core/entities/player/GCPlayerHandler.java

Prevent division by zero with thermalLevelTickCooldownSingle in case thermalLevelMod significantly bigger/less.
Issue occurs when using mod MorePlanets on Venus, that is hot :D

Prevent division by zero with thermalLevelTickCooldownSingle

---

src/main/java/micdoodle8/mods/galacticraft/core/util/WorldUtil.java

When the overworld dimension is set to an different id than 0, this code takes the wrong provider to get the name.
So when the overworld is also called different, this will crash the server, when trying to reenter the "Overworld" from a planet.
Maybe related: #2242
Should fix #2243

Fixes server crash when Overworld id is not 0

---

src/main/java/micdoodle8/mods/galacticraft/core/world/ChunkLoadingCallback.java

The chunkLoaderList is only saved to disk when it has changed, preventing some lag that was detected after profilling,
I also saw that the entries of this list are never removed, even when the block is broken, isn't it a bug?

Only save the chunkLoaderList to disk when changed

---

src/main/resources/assets/galacticraftplanets/mcmod.info

It wasn't recognized by Forge because the Mod ID was wrong. I also updated the mod version and the MC version.

Fix GC Planets mcmod.info

---

src/main/java/micdoodle8/mods/galacticraft/core/tile/TileEntityOxygenDistributor.java

Found this while trying to re-enable redstone control in my own fork (since applying redstone makes this false and the bubble distrib didn't care.) Not huge but just something that seemed forgotten.

Bubble Distributor doesn't "hasEnoughEnergyToRun"

---

src/main/java/micdoodle8/mods/galacticraft/api/GalacticraftConfigAccess.java
src/main/java/micdoodle8/mods/galacticraft/api/recipe/CompressorRecipes.java
src/main/java/micdoodle8/mods/galacticraft/core/entities/EntityEvolvedCreeper.java
src/main/java/micdoodle8/mods/galacticraft/core/entities/EntityEvolvedSkeleton.java
src/main/java/micdoodle8/mods/galacticraft/core/entities/EntityEvolvedSpider.java
src/main/java/micdoodle8/mods/galacticraft/core/entities/EntityEvolvedZombie.java
src/main/java/micdoodle8/mods/galacticraft/core/entities/player/GCPlayerHandler.java
src/main/java/micdoodle8/mods/galacticraft/core/event/EventHandlerGC.java
src/main/java/micdoodle8/mods/galacticraft/core/util/ConfigManagerCore.java
src/main/java/micdoodle8/mods/galacticraft/core/util/WorldUtil.java
src/main/java/micdoodle8/mods/galacticraft/planets/asteroids/world/gen/ChunkProviderAsteroids.java

This adds separate settings to enable the compressor recipes, mob drops/spawns, spawn handling, and asteroid population from the asteroid challenge mode.
For example, this would allow someone to use their own spawn control system to customize players' starting positions and materials, but keep the added recipes and mob drops and spawns. One could also use these settings to keep the challenge mode player spawning and asteroid population, but set up their own mob drops and recipes.
I placed all the new config settings into the API's config access, since I didn't know if other mod authors might one day find it useful to know what individual parts of the challenge mode are enabled. I only added the challenge recipes setting to the server config override, since this was the only individual …

Added config settings for separately enabling parts of challenge mode

---

src/main/java/micdoodle8/mods/galacticraft/core/client/render/entities/layer/LayerFrequencyModule.java
src/main/java/micdoodle8/mods/galacticraft/core/client/render/entities/layer/LayerOxygenGear.java
src/main/java/micdoodle8/mods/galacticraft/core/client/render/entities/layer/LayerOxygenTanks.java

Fix Oxygen Gear and Frequency Module rendering

---

src/main/java/micdoodle8/mods/galacticraft/core/items/ItemTier1Rocket.java

`ItemTier1Rocket` should return `SUCCESS` (just like `ItemTier2Rocket` and `ItemTier3Rocket` already do) when it consumes an item.
Normally, this doesn't cause any issues but SpongeForge is a bit more strict about the return values and will restore the item unless the handler returned `SUCCESS`, which makes it possible to place infinite rockets.
Might be related to issue 1 of #2953 if it only happened with tier 1 rockets.

Return SUCCESS in ItemTier1Rocket after consuming item

---

src/main/java/micdoodle8/mods/galacticraft/planets/venus/entities/EntitySpiderQueen.java

I found a sponge issue with my addon and adding this to my entity class fixes it, i also saw that this is the only boss that didn't have this function in it in Galacticraft so this should fix this issue for you :D

Fix Sponge issue for Spider Queen Boss not dropping a key

---

src/main/java/micdoodle8/mods/galacticraft/core/tile/TileEntityScreen.java

Sorry I couldn't give an update on the master branch, I wasn't able to get it to run properly. Not sure what the equivalent is in master, but it will need to be tweaked for other Minecraft versions. Looks like older versions had getDescriptionPacket?

Override getUpdateTag() in TileEntityScreen to send the correct data to the client (for #3032).

---

src/main/java/micdoodle8/mods/galacticraft/core/GalacticraftCore.java

let it load after TiCo to prevent missing "tile.unlitTorch_Stone" errors.

[1.7.10]Changed Dependencies to prevent missing "tile.unlitTorch_Stone" errors.

---

src/main/java/micdoodle8/mods/galacticraft/planets/asteroids/ConfigManagerAsteroids.java

It seems that the default value [changed](https://github.com/micdoodle8/Galacticraft/commit/bb7a16562d28e3f185edaa200bc199242739463d#diff-15fc6195c29b4495451976190a2ba562l) since the config was added.

Correct description for maximumAstroMiners

---

src/main/java/micdoodle8/mods/galacticraft/core/util/GCLog.java

(Follow-up of #3179 )
This time it's in 1.12 and has no 1 line changes :)
Note: This is compatible with 1.8-1.12.2.

[1.12] Stop using deprecated logging

---

src/main/java/micdoodle8/mods/galacticraft/core/client/gui/screen/GuiCelestialSelection.java

Only needed 1.10+ since it only exists above 1.8 in the constructor for GuiCelestialSelection
Needed to solve my issue of https://github.com/MJRLegends/ExtraPlanets/issues/300 since i need to get the value from GuiCelestialSelection that was sent and parse it to my custom screen. (i already do this for List<CelestialBody> possibleBodies since that one is already public not protected)
Any more questions please let me know

Change canCreateStations variable to public

---

src/main/java/micdoodle8/mods/galacticraft/core/world/gen/dungeon/RoomBoss.java

Ok so in https://github.com/DarkPacks/SevTech-Ages/issues/2175 issue someone reported a issue where it would crash on a ExtraPlanets dungeon. I debugged this back to just a bad seed and just needs a simple null point checker to stop the crash and allow the dungeon just be not usable
See comments over at the issue for a screenshot/more info on this

Fixed possible dungeon crash issue

---

src/main/java/micdoodle8/mods/galacticraft/core/GCItems.java

Whilst using food mods such as Pam's Harvestcraft Galacticraft Cheese cannot be used in recipes.

Added OreDictionary value for Cheese Curd

---

src/main/java/micdoodle8/mods/galacticraft/core/GalacticraftCore.java
src/main/java/micdoodle8/mods/galacticraft/planets/asteroids/AsteroidsModule.java
src/main/java/micdoodle8/mods/galacticraft/planets/asteroids/recipe/RecipeManagerAsteroids.java
src/main/java/micdoodle8/mods/galacticraft/planets/mars/MarsModule.java
src/main/java/micdoodle8/mods/galacticraft/planets/mars/recipe/RecipeManagerMars.java
src/main/java/micdoodle8/mods/galacticraft/planets/venus/VenusModule.java
src/main/java/micdoodle8/mods/galacticraft/planets/venus/recipe/RecipeManagerVenus.java

Fixes https://github.com/micdoodle8/Galacticraft/issues/3514
This pull requests move everything that isnt mod compact recipes to the RegistryEvent.Register<IRecipe> event to match the GC Core which already has this. 
I need this to fix GalacticraftTweaker issues
https://github.com/MJRLegends/GalacticraftTweaker/issues/4
https://github.com/MJRLegends/GalacticraftTweaker/issues/6
Would be amazing if it could be merged

1.12.2 only, Changed GC Planets registering recipes to match GC Core system

---

build.gradle

I couldn't really find a appropriate place to put this, so I just made this PR. It just updates the revision/patch version to 2 to match the mod's metadata (So that the file's version matches the mod's version.
Edit: While the topic is still sort-of on `build.gradle` - Why do you guys use a `dependencies/` folder instead of using maven repos?

Update "versionRev" to 2

---

src/main/java/micdoodle8/mods/galacticraft/core/items/ItemBattery.java
src/main/java/micdoodle8/mods/galacticraft/core/items/ItemCanisterGeneric.java
src/main/java/micdoodle8/mods/galacticraft/core/items/ItemFuelCanister.java
src/main/java/micdoodle8/mods/galacticraft/core/items/ItemOilCanister.java
src/main/java/micdoodle8/mods/galacticraft/core/items/ItemOxygenTank.java

Note: To be tested on 1.10+ (but I'm pretty sure the method has not changed)

Disable enchants on special items with durability (Fix #3626)

---

src/main/java/micdoodle8/mods/galacticraft/core/entities/EntityMeteor.java

I was trying to understand the Meteor impact code, and I came across a section where variables were named `var2`, `var3`, etc. My guess is that someone copied and pasted this from decompiled vanilla code. I renamed them to something that looks sensible to me.
My apologies if this doesn't meet the contributing guidelines, as it doesn't fix anything and is really just a refactoring commit. Even if it's not merged, this exercise was helpful for me in understanding this code.

Readability refactoring: Gave meaningful names to var2 - var15

---

src/main/java/micdoodle8/mods/galacticraft/planets/mars/entities/EntityCreeperBoss.java

And the method 'setSwingingArms' seems unused.

Fixed Creeper Boss ignore /kill command

---

src/main/java/micdoodle8/mods/galacticraft/planets/asteroids/ConfigManagerAsteroids.java
src/main/java/micdoodle8/mods/galacticraft/planets/asteroids/entities/player/AsteroidsPlayerHandler.java
src/main/resources/assets/galacticraftplanets/lang/en_US.lang

A handful of server owners on the GC discord seem to still have lag problems with small asteroids, even after https://github.com/micdoodle8/Galacticraft/commit/579479ab4a64b0133177b552602c290c6a196cc3, so I made a config option to disable the asteroids entirely.

Add an option to disable small asteroids entirely

---

src/main/java/micdoodle8/mods/galacticraft/core/client/SkyProviderOrbit.java

After much debugging, figured out that SkyProviderOrbit is being instantiated many times. It seems like it was originally designed to be instantiated once/a small number of times, then render() called on it many times.
Instantiating this class many, many times was leading to a memory leak where many copies of the openGL display lists were instantiated but never free'd.
This patch changes those display lists to only instantiate once and be re-used by any subsequent instance of SkyProviderOrbit. This should fix the memory leak and improve overall rendering performance.
Somewhat anecdotal, but this brings my FPS from ~20 to my monitor's 120 vsync. The sky still animates on my space station... seems to work well but not sure how else to test this.

Only initialize render lists in SkyProviderOrbit once (fix client memory leak, greatly improve space station FPS)
